# Generated by Django 4.1.13 on 2024-08-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('profile_img', models.ImageField(default='/static/media/user/profile.png', upload_to='')),
                ('email_verify', models.BooleanField()),
                ('phone_verify', models.BooleanField()),
            ],
        ),
    ]
